export const STUDENT_LIST = "STUDENT_LIST";
export const STUDENT_LIST_SUCCESS = "STUDENT_LIST_SUCCESS";
export const STUDENT_LIST_FAILED = "STUDENT_LIST_FAILED";

export const STUDENT_LIST_ADD = "STUDENT_LIST_ADD";
export const STUDENT_LIST_ADD_SUCCESS = "STUDENT_LIST_ADD_SUCCESS";
export const STUDENT_LIST_ADD_FAILED = "STUDENT_LIST_ADD_FAILED";

export const STUDENT_LIST_DELETE = "STUDENT_LIST_DELETE";
export const STUDENT_LIST_DELETE_SUCCESS = "STUDENT_LIST_DELETE_SUCCESS";
export const STUDENT_LIST_DELETE_FAILED = "STUDENT_LIST_DELETE_FAILED";

export const STUDENT_LIST_GET = "STUDENT_LIST_GET";
export const STUDENT_LIST_GET_SUCCESS = "STUDENT_LIST_GET_SUCCESS";
export const STUDENT_LIST_GET_FAILED = "STUDENT_LIST_GET_FAILED";
