export const STUDENT_LIST = "STUDENT_LIST";
export const STUDENT_LIST_SUCCESS = "STUDENT_LIST_SUCCESS";
export const STUDENT_LIST_FAILED = "STUDENT_LIST_FAILED";

export const STUDENT_LIST_ADD = "STUDENT_LIST_ADD";
export const STUDENT_LIST_ADD_SUCCESS = "STUDENT_LIST_ADD_SUCCESS";
export const STUDENT_LIST_ADD_FAILED = "STUDENT_LIST_ADD_FAILED";

